#!/bin/sh


cmd="rofi -theme $HOME/.config/rofi/menu.rasi"

pm() {
  sd=""
  rb=""
  lk=""
  lg="" && [ -n "$(ls $ssdir)" ] || open=""

  options="$sd\n$rb\n$lk\n$lg\n"
  chosen="$(printf "$options" | $cmd -dmenu)"

  confirm() {
    yes=""
    no=""
    cmd="rofi -theme $HOME/.config/rofi/ok.rasi"
    options="$yes\n$no\n";
    a="$(printf "$options" | $cmd -dmenu -selected-row 1)"
    case $a in 
      $yes) continue;;
      $no|*) exit 1;;
    esac
  }

  [ -n "$chosen" ] && confirm

  case $chosen in 
    $sd) loginctl poweroff;;
    $rb) loginctl reboot;;
    $lk) $HOME/.local/bin/lock;;
    $lg) bspc quit;;
  esac
}
ss() {
  ssdir="$HOME/Pictures/ScreenShots"

  shot=""
  full=""
  sav=""
  open="" && [ -n "$(ls $ssdir)" ] || open=""

  options="$shot\n$full\n$sav\n$open\n"
  chosen="$(printf "$options" | $cmd -dmenu)"

  case $chosen in 
    $shot) maim -usb 5 | xclip -selection clipboard -t image/png && notify-send "ScreenShot" "Selection Copied";;
    $full) maim $ssdir/$(date +%j_%y_%S).png && notify-send "ScreenShot" "FullScreen Saved";;
    $sav) maim -usb 5 $ssdir/$(date +%j_%y_%S).png && notify-send "ScreenShot" "Selection Saved";;
    $open) kitty $ssdir;;
  esac
}

$1
