[[ $- != *i* ]] && return
alias ls='ls --color=auto'
alias cls='clear'
alias py='python3'
alias pip='pip3'
alias ytdl='youtube-dl'
alias docker='sudo docker'
alias open='xdg-open'
alias xr='sudo xbps-remove'
alias xi='sudo xbps-install'
alias xq='sudo xbps-query'
PS1='\033[1;35m\w/ → \033[1;0m'
