#!/bin/sh

#Autostart
picom -b &
killall sxhkd; sxhkd &
killall dunst; dunst &
feh --bg-fill -r -z $HOME/Pictures/Wallpapers &
redshift -x && redshift -O 4000k &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &

#variable
alias bc='bspc config'
alias br='bspc rule'

#Workspaces
bspc monitor -d 1 2 3 4 5 6 7

#Others
bc border_width 0
bc window_gap 10
bc split_ratio 0.50
bc borderless_monocle true
bc gapless_monocle false
bc focus_follows_pointer true

#rules
br -a feh state=floating
br -a sxiv state=floating
br -a mpv state=floating
