#! /bin/sh

##########################
# autostart applications #
##########################

sxhkd &
picom &
dunst &
feh --bg-fill -r -z ~/Pictures/Wallpapers &
xbacklight -set 10 &
redshift -x && redshift -O 4500k &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &

alias bc='bspc config'
alias br='bspc rule'

# workspace names
bspc monitor -d 1 2 3 4 5 6 7

# borders and gaps
bc border_width         0
bc window_gap           15

# others
bc split_ratio          0.50
bc borderless_monocle   true
bc gapless_monocle      false
bc focus_follows_pointer true
