#!/bin/sh

#Autostart
picom -b &
killall sxhkd; sxhkd &
killall dunst; dunst -print > .cache/dunst.log &
feh --bg-fill -r -z $HOME/Pictures/Wallpapers &
redshift -x && redshift -O 4000k &
xsetroot -cursor_name left_ptr &
killall flameshot; flameshot &
# $HOME/.config/polybar/launch.sh &
killall tint2; tint2 &

#variable
alias bc='bspc config'
alias br='bspc rule'
c="#1f1f1f"

#Workspaces
bspc monitor -d 1 2 3 4 5 6 7

#Others
bc border_width 0
bc normal_border_color "$c"
bc focused_border_color "$c"
bc active_border_color "$c"
bc window_gap 10
bc split_ratio 0.50
bc borderless_monocle true
bc gapless_monocle false
bc focus_follows_pointer true

#rules
br -a feh state=floating
br -a mpv state=floating

bspc subscribe node_state | while read -r _ _ _ _ state flag; do
  if [ "$state" != "fullscreen" ]; then
    continue
  fi
  if [ "$flag" == on ]; then
    br -a tint2 layer=bottom
  else
    br -a tint2 layer=top
  fi
done
