#!/bin/sh

conf() {
  printf "
  (\ /)    $(c 0 31)  kr$(c 0 37) $(Kernel)
  ( · ·)   $(c 0 34)  os$(c 0 37) $(Os)
  c($(c 0 31)\"$(c 0 37))($(c 0 31)\"$(c 0 37))  $(c 0 32)  sh$(c 0 37) $(Shell)
  \n"
}
