#!/bin/sh

conf() {
  printf "
  $(c 1 34)$(Name)
  $(c 1 37)Os: $(Os)
  Kernel: $(Kernel)
  Shell: $(Shell)
  DE/WM: $(Desktop)

  $(c 1 90)  $(c 1 31)  $(c 1 32)  $(c 1 33)  $(c 1 34)  $(c 1 35)  $(c 1 36)  $(c 1 37)  $(c 0 0)
  \n"
}
